locations = {
    "T'ai-pei": "Taiwan",
    "T'ai-wan": "Taiwan",
    "Vilniaus Apskritis": "Lithuania",
    "Kauno Apskritis": "Lithuania",
    "Limassol": "Cyprus",
    "Larnaca": "Cyprus",
    "Dhaka": "Bangladesh",
    "Lima": "Peru",
    "Distrito Federal": "Brazil",
    "Santa Fe": "Argentina",
    "Cordoba": "Argentina",
    "Hovedstaden": "Denmark",
    "Midtjylland": "Denmark",
    "Syddanmark": "Denmark",
    "Nordjylland": "Denmark",
    "Southern Finland": "Finland",
    "Oulu": "Finland",
    "Western Finland": "Finland",
    "Eastern Finland": "Finland",
    "Stockholms Lan": "Sweden",
    "Vastra Gotaland": "Sweden",
    "Ostergotlands Lan": "Sweden",
    "Uppsala Lan": "Sweden",
    "Vastmanlands Lan": "Sweden",
    "Skane Lan": "Sweden",
    "Norrbottens Lan": "Sweden",
    "Vasterbottens Lan": "Sweden",
    "Kronobergs Lan": "Sweden",
    "Pennsylvania": "United States",
    "Georgia": "United States",
    "Washington": "United States",
    "Massachusetts": "United States",
    "Florida": "United States",
    "District of Columbia": "United States",
    "Ohio": "United States",
    "California": "United States",
    "Illinois": "United States",
    "Minnesota": "United States",
    "Virginia": "United States",
    "Colorado": "United States",
    "Maryland": "United States",
    "Michigan": "United States",
    "Texas": "United States",
    "Indiana": "United States",
    "North Carolina": "United States",
    "Utah": "United States",
    "Connecticut": "United States",
    "Missouri": "United States",
    "Tennessee": "United States",
    "Wisconsin": "United States",
    "New Jersey": "United States",
    "Nebraska": "United States",
    "Arizona": "United States",
    "New Hampshire": "United States",
    "Oregon": "United States",
    "Kansas": "United States",
    "Quezon City": "Philippines",
    "Manila": "Philippines",
    "Rizal": "Philippines",
    "Cavite": "Philippines",
    "Victoria": "Australia",
    "Queensland": "Australia",
    "New South Wales": "Australia",
    "Australian Capital Territory": "Australia",
    "Western Australia": "Australia",
    "South Australia": "Australia",
    "Malopolskie": "Poland",
    "Mazowieckie": "Poland",
    "Dolnoslaskie": "Poland",
    "Wielkopolskie": "Poland",
    "Zachodniopomorskie": "Poland",
    "Lubelskie": "Poland",
    "Region Metropolitana": "Chile",
    "Central Region": "Singapore",
    "North Region": "Singapore",
    "Dubai": "United Arab Emirates",
    "Abu Dhabi": "United Arab Emirates",
    "Haryana": "India",
    "Uttar Pradesh": "India",
    "Maharashtra": "India",
    "Karnataka": "India",
    "Andhra Pradesh": "India",
    "Delhi": "India",
    "Tamil Nadu": "India",
    "Bihar": "India",
    "Gujarat": "India",
    "West Bengal": "India",
    "Rajasthan": "India",
    "Nuevo Leon": "Mexico",
    "Jalisco": "Mexico",
    "Queretaro de Arteaga": "Mexico",
    "Chiapas": "Mexico",
    "Morelos": "Mexico",
    "Distrito Especial": "Colombia",
    "Antioquia": "Colombia",
    "Valle del Cauca": "Colombia",
    "Atlantico": "Colombia",
    "Jakarta Raya": "Indonesia",
    "Jawa Barat": "Indonesia",
    "Hong Kong Island": "Hong Kong",
    "New Territories": "Hong Kong",
    "Kowloon": "Hong Kong",
    "Grad Zagreb": "Croatia",
    "Zagrebacka": "Croatia",
    "Kuala Lumpur": "Malaysia",
    "Perak": "Malaysia",
    "Selangor": "Malaysia",
    "Riga": "Latvia",
    "Rezeknes": "Latvia",
    "Tukuma": "Latvia",
    "Wien": "Austria",
    "Oberosterreich": "Austria",
    "Steiermark": "Austria",
    "Lisboa": "Portugal",
    "Porto": "Portugal",
    "Braga": "Portugal",
    "Bucuresti": "Romania",
    "Sibiu": "Romania",
    "Punjab": "Pakistan",
    "Sindh": "Pakistan",
    "Islamabad": "Pakistan",
    "Hlavni mesto Praha": "Czech Republic",
    "Jihomoravsky kraj": "Czech Republic",
    "Akershus": "Norway",
    "Sor-Trondelag": "Norway",
    "Oslo": "Norway",
    "Sogn og Fjordane": "Norway",
    "More og Romsdal": "Norway",
    "Hordaland": "Norway",
    "Rogaland": "Norway",
    "Ostfold": "Norway",
    "Nordland": "Norway",
    "Brussels Hoofdstedelijk Gewest": "Belgium",
    "Oost-Vlaanderen": "Belgium",
    "Brabant Wallon": "Belgium",
    "Antwerpen": "Belgium",
    "Limburg": "Belgium",
    "Vlaams-Brabant": "Belgium",
    "West-Vlaanderen": "Belgium",
    "Liege": "Belgium",
    "Hainaut": "Belgium",
    "Ontario": "Canada",
    "Tokyo": "Japan",
    "Chiba": "Japan",
    "Kanagawa": "Japan",
    "Yamagata": "Japan",
    "Kyoto": "Japan",
    "Fukuoka": "Japan",
    "Fukushima": "Japan",
    "Kumamoto": "Japan",
    "Fukui": "Japan",
    "NA - Vietnam": "Vietnam",
    "Bayern": "Germany",
     "Berlin": "Germany",
    "Nordrhein-Westfalen": "Germany",
    "Baden-Wurttemberg": "Germany",
    "Hamburg": "Germany",
    "Hessen": "Germany",
    "Sachsen": "Germany",
    "Rheinland-Pfalz": "Germany",
    "Niedersachsen": "Germany",
    "Bremen": "Germany",
    "NA - Malta": "Malta",
    "Ar Riyad": "Saudi Arabia",
    "Ha'il": "Saudi Arabia",
    "Makkah": "Saudi Arabia",
    "Ash Sharqiyah": "Saudi Arabia",
    "Dublin": "Ireland",
    "Wexford": "Ireland",
    "Mayo": "Ireland",
    "Galway": "Ireland",
    "Cork": "Ireland",
    "Waterford": "Ireland",
    "Kyonggi-do": "South Korea",
    "Seoul-t'ukpyolsi": "South Korea",
    "Pusan-jikhalsi": "South Korea",
    "Cheju-do": "South Korea",
    "Kyongsang-bukto": "South Korea",
    "Sao Paulo": "Brazil",
    "Parana": "Brazil",
    "Minas Gerais": "Brazil",
    "Ceara": "Brazil",
    "Rio de Janeiro": "Brazil",
    "Rio Grande do Sul": "Brazil",
    "Santa Catarina": "Brazil",
    "Bahia": "Brazil",
    "Goias": "Brazil",
    "Rio Grande do Norte": "Brazil",
    "Krung Thep": "Thailand",
    "Samut Sakhon": "Thailand",
    "Phuket": "Thailand",
    "Attiki": "Greece",
    "Ljubljana Urban Commune": "Slovenia",
    "Trbovlje Commune": "Slovenia",
    "Noord-Brabant": "Netherlands",
    "Noord-Holland": "Netherlands",
    "Utrecht": "Netherlands",
    "Zuid-Holland": "Netherlands",
    "Gelderland": "Netherlands",
    "Grad Sofiya": "Bulgaria",
    "Luxembourg": "Luxembourg",
    "Ile-de-France": "France",
    "Rhone-Alpes": "France",
    "Midi-Pyrenees": "France",
    "Provence-Alpes-Cote d'Azur": "France",
    "Bretagne": "France",
    "Languedoc-Roussillon": "France",
    "Nord-Pas-de-Calais": "France",
    "Pays de la Loire": "France",
    "Aquitaine": "France",
    "Picardie": "France",
    "Haute-Normandie": "France",
    "Auckland": "New Zealand",
    "Otago": "New Zealand",
    "Gisborne": "New Zealand",
    "Bay of Plenty": "New Zealand",
    "Nelson": "New Zealand",
    "Bratislava": "Slovakia",
    "Budapest": "Hungary",
    "Madrid": "Spain",
    "Catalonia": "Spain",
    "Comunidad Valenciana": "Spain",
    "Castilla y Leon": "Spain",
    "Andalucia": "Spain",
    "Pais Vasco": "Spain",
    "Galicia": "Spain",
    "Canarias": "Spain",
    "Islas Baleares": "Spain",
    "Aragon": "Spain",
    "Asturias": "Spain",
    "Toscana": "Italy",
    "Lombardia": "Italy",
    "Emilia-Romagna": "Italy",
    "Lazio": "Italy",
    "Campania": "Italy",
    "Veneto": "Italy",
    "Friuli-Venezia Giulia": "Italy",
    "Gullbringusysla": "Iceland",
    "Vestur-Isafjardarsysla": "Iceland",
    "Guangdong": "China",
    "Beijing": "China",
    "Shanghai": "China",
    "Zhejiang": "China",
    "Jiangsu": "China",
    "Sichuan": "China",
    "Hainan": "China",
    "Hunan": "China",
    "Fujian": "China",
    "Jiangxi": "China",
    "Hebei": "China",
    "Liaoning": "China",
    "Shaanxi": "China",
    "Hubei": "China",
    "Shandong": "China",
    "Chongqing": "China",
    "Guangxi": "China",
    "Heilongjiang": "China",
    "Jilin": "China",
    "Harjumaa": "Estonia",
    "Al Kuwayt": "Kuwait"
}